Fixed Issue Found by Ace in FML
Error Ace was getting was

Exception in RunningCoroutine: ReArmature.ReArmature+ReplaceOldMesh+<Process>d__1
System.MissingMethodException: FrooxEngine.Slot FrooxEngine.Slot.Duplicate(FrooxEngine.Slot,bool,FrooxEngine.DuplicationSettings)

After looking at the Duplicate function it was expecting 4 values to be passed so I just added the missing defualts

I also edited the csproj so on build copies the DLL to mods folder and has a path property.